#!/bin/env php
<?php require __DIR__ . '/vendor/autoload.php';

$username = 'username';
$password = 'password';

use BapCat\Phi\Phi;
use BapCat\UniFi\UniFi;
use BapCat\UniFi\Actions;

$ioc = Phi::instance();

$unifi = new UniFi($ioc);
$unifi->login($username, $password, function(Actions $actions) {
  echo json_encode(json_decode((string)$actions->staStats('default')->getBody()), JSON_PRETTY_PRINT);
  //$actions->authorize('default', '00:00:00:00:00:00', 1);
});
